[2023-03-29T07:02:30.186+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-27T16:30:00+00:00 [queued]>
[2023-03-29T07:02:30.192+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-27T16:30:00+00:00 [queued]>
[2023-03-29T07:02:30.192+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T07:02:30.192+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-03-29T07:02:30.192+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T07:02:30.218+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2023-03-27 16:30:00+00:00
[2023-03-29T07:02:30.224+0000] {standard_task_runner.py:55} INFO - Started process 361368 to run task
[2023-03-29T07:02:30.232+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', 'scheduled__2023-03-27T16:30:00+00:00', '--job-id', '490', '--raw', '--subdir', 'DAGS_FOLDER/test_docker_operator.py', '--cfg-path', '/tmp/tmp77febf0k']
[2023-03-29T07:02:30.234+0000] {standard_task_runner.py:83} INFO - Job 490: Subtask docker_op_tester
[2023-03-29T07:02:30.296+0000] {task_command.py:389} INFO - Running <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-27T16:30:00+00:00 [running]> on host vibrdairflow.tciw5gv3lhjetcyg0kqzfvdylc.hx.internal.cloudapp.net
[2023-03-29T07:02:30.382+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T16:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-27T16:30:00+00:00
[2023-03-29T07:02:30.385+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azureuser/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 431, in execute
    if self.force_pull or not self.cli.images(name=self.image):
  File "/home/azureuser/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 302, in cli
    return self.hook.api_client
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/azureuser/.local/lib/python3.8/site-packages/airflow/providers/docker/hooks/docker.py", line 118, in api_client
    client = APIClient(
  File "/home/azureuser/.local/lib/python3.8/site-packages/docker/api/client.py", line 136, in __init__
    base_url = utils.parse_host(
  File "/home/azureuser/.local/lib/python3.8/site-packages/docker/utils/utils.py", line 274, in parse_host
    raise errors.DockerException(
docker.errors.DockerException: Invalid bind address format: port is required: https://registry.hub.docker.com/v2/
[2023-03-29T07:02:30.389+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20230327T163000, start_date=20230329T070230, end_date=20230329T070230
[2023-03-29T07:02:30.411+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 490 for task docker_op_tester (Invalid bind address format: port is required: https://registry.hub.docker.com/v2/; 361368)
[2023-03-29T07:02:30.441+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-29T07:02:30.463+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
