[2023-03-29T06:42:55.961+0000] {taskinstance.py:1077} INFO - Dependencies not met for <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-27T09:10:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-03-29T06:42:55.961369+00:00 and task will be retried at 2023-03-29T06:47:48.799081+00:00.
[2023-03-29T06:42:55.962+0000] {local_task_job.py:98} INFO - Task is not able to be run
[2023-03-29T06:47:55.623+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-27T09:10:00+00:00 [queued]>
[2023-03-29T06:47:55.630+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-27T09:10:00+00:00 [queued]>
[2023-03-29T06:47:55.630+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T06:47:55.630+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-03-29T06:47:55.630+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T06:47:55.655+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2023-03-27 09:10:00+00:00
[2023-03-29T06:47:55.660+0000] {standard_task_runner.py:55} INFO - Started process 337857 to run task
[2023-03-29T06:47:55.666+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', 'scheduled__2023-03-27T09:10:00+00:00', '--job-id', '337', '--raw', '--subdir', 'DAGS_FOLDER/test_docker_operator.py', '--cfg-path', '/tmp/tmp3jpqgpat']
[2023-03-29T06:47:55.668+0000] {standard_task_runner.py:83} INFO - Job 337: Subtask docker_op_tester
[2023-03-29T06:47:55.731+0000] {task_command.py:389} INFO - Running <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-27T09:10:00+00:00 [running]> on host vibrdairflow.tciw5gv3lhjetcyg0kqzfvdylc.hx.internal.cloudapp.net
[2023-03-29T06:47:55.791+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T09:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-27T09:10:00+00:00
[2023-03-29T06:47:55.794+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azureuser/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 431, in execute
    if self.force_pull or not self.cli.images(name=self.image):
  File "/home/azureuser/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 302, in cli
    return self.hook.api_client
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/azureuser/.local/lib/python3.8/site-packages/airflow/providers/docker/hooks/docker.py", line 118, in api_client
    client = APIClient(
  File "/home/azureuser/.local/lib/python3.8/site-packages/docker/api/client.py", line 136, in __init__
    base_url = utils.parse_host(
  File "/home/azureuser/.local/lib/python3.8/site-packages/docker/utils/utils.py", line 274, in parse_host
    raise errors.DockerException(
docker.errors.DockerException: Invalid bind address format: port is required: https://registry.hub.docker.com/v2/
[2023-03-29T06:47:55.799+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20230327T091000, start_date=20230329T064755, end_date=20230329T064755
[2023-03-29T06:47:55.824+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 337 for task docker_op_tester (Invalid bind address format: port is required: https://registry.hub.docker.com/v2/; 337857)
[2023-03-29T06:47:55.837+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-29T06:47:55.855+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
